GET {{host}}/User/login/false
Accept: application/json
###

POST {{host}}/Resources
Content-Type: application/json

{
  "name": "How to become an ambtenaar",
  "description": "Information on how to become a abmteraar",
  "source": "https://www.bol.com/nl/nl/p/hoe-word-ik-een-echte-ambtenaar/9200000006236974/",
  "comments": [
    "Be come a really good ambetanaar",
    "Don't do it"
  ]
}

###
POST {{host}}/Resources
Content-Type: application/json

{
  "name": "How to become an Developer",
  "description": "Information on how to type ones and zero's",
  "source": "https://www.youtube.com/watch?v=zDNaUi2cjv4",
  "comments": [
    "Now i know ho to type 1010",
    "0000"
  ]
}

###

GET {{host}}/Resources/0eeced3f-89c4-4d9a-851a-a6c17c8e0f7b
Accept: application/json

###
GET {{host}}/Resources/
Accept: application/json

###
DELETE {{host}}/Resources/04b84330-a8aa-432e-a747-ab13aa2cf719
Accept: application/json

###

GET {{host}}/User/logout
Accept: application/json
###

